"""Generate src/libs/han_fold_table.h (usage: python tools/gen_han_fold.py [out.h]): code point -> canonical (Japanese shinjitai) form.
Sources: OpenCC STCharacters.txt (simplified -> traditional, first candidate) and
JPShinjitaiCharacters.txt (shinjitai -> kyujitai variants, reversed here)."""
import os, sys
here = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(here, 'opencc_data')
out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, '..', 'src', 'libs', 'han_fold_table.h')
os.makedirs(D, exist_ok=True)
for name in ('STCharacters.txt', 'JPShinjitaiCharacters.txt'):
    if not os.path.exists(os.path.join(D, name)):
        import urllib.request
        urllib.request.urlretrieve('https://raw.githubusercontent.com/BYVoid/OpenCC/master/data/dictionary/' + name,
                                   os.path.join(D, name))

def load(name):
    rows = []
    for line in open(os.path.join(D, name), encoding='utf-8'):
        if not line.strip() or line.startswith('#'): continue
        k, v = line.rstrip('\n').split('\t', 1)
        rows.append((k, v.split()))
    return rows

st = {}                                    # simplified -> traditional (first candidate)
for k, vs in load('STCharacters.txt'):
    if len(k) == 1 and vs and len(vs[0]) == 1:
        st[k] = vs[0]
tj = {}                                    # traditional (kyujitai) -> shinjitai
for jp, vs in load('JPShinjitaiCharacters.txt'):
    if len(jp) != 1: continue
    for v in vs:
        if len(v) == 1 and v != jp and v not in tj:
            tj[v] = jp

def fold(c):
    c = st.get(c, c)
    c = tj.get(c, c)
    return c

table = {}
for c in set(st) | set(tj):
    f = fold(c)
    if f != c:
        table[ord(c)] = ord(f)
pairs = sorted(table.items())
with open(out, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write('// Generated by gen_han_fold.py from OpenCC STCharacters.txt + JPShinjitaiCharacters.txt\n')
    fh.write('// (Apache-2.0, https://github.com/BYVoid/OpenCC). Maps a simplified or traditional\n')
    fh.write('// Chinese character to its Japanese shinjitai form so Song Search matches across scripts.\n')
    fh.write('#pragma once\n#include <cstdint>\n#include <cstddef>\n\n')
    fh.write('struct HanFoldPair { uint32_t from, to; };\n')
    fh.write('static constexpr HanFoldPair HAN_FOLD_TABLE[] = {\n')
    for i in range(0, len(pairs), 8):
        fh.write('    ' + ' '.join('{0x%04X,0x%04X},' % p for p in pairs[i:i+8]) + '\n')
    fh.write('};\n')
    fh.write('static constexpr size_t HAN_FOLD_TABLE_SIZE = sizeof(HAN_FOLD_TABLE) / sizeof(HAN_FOLD_TABLE[0]);\n')
print(len(pairs), 'entries ->', out)
